
apex deploy  \
    -s "SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" \
    -s "ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" \
    -s "REGION=$AWS_REGION" \
    -s "GOOGLE_KEY=$GOOGLE_KEY" \
    -s "BOT_KEY=$TELEGRAM_BOT_KEY" \
    -s "YANDEX_SPEECHKIT_KEY=$YANDEX_SPEECHKIT_KEY" \
    $*
